### ISSUE TITLE
in runMode = predictAll -> NameError: name 'train_normexpr' is not defined

### ISSUE THREAD

**Issue by jp089** [devCellPy-Team/devCellPy#3]
Hello, 
So I did the training, and now I make a subset of the same data, to do an "external quality control" in order to validate the training.
So after running the training runMode=trainAll, I tried to run  runMode=predictAll:

devcellpy --runMode predictAll \
--predNormExpr /subset_normalized_expression.csv \
--layerObjectPaths /Root/Root_object.pkl,/Root/A/Aobject.pkl,/Root/B/B_object.pkl,/Root/C/C_object.pkl \
--rejectionCutoff 0.5

[<Layer: 'Root', Level: 0, labeldict: {0: 'Basophils', 1: 'Monocytes', 2: 'Neutrophils', 3: 'Myeloids', 4: 'B cells', 5: 'T cells', 6: 'NK', 7: 'Hepatocytes', 8: 'Cholangiocytes', 9: 'Endothelial cells', 10: 'Fibroblasts'}, Trained: True>, <Layer: 'NK', Level: 1, labeldict: {0: 'Circulating NK/NKT', 1: 'Resident NK'}, Trained: True>, <Layer: 'Myeloids', Level: 1, labeldict: {0: 'cDC1s', 1: 'cDC2s', 2: 'Mig.cDCs', 3: 'pDCs', 4: 'Plasma cells'}, Trained: True>, <Layer: 'Monocytes', Level: 1, labeldict: {0: 'Macrophages', 1: 'Mono+mono derived cells'}, Trained: True>]
Traceback (most recent call last):
  File "/home/pablo/.local/bin/devcellpy", line 8, in <module>
    sys.exit(main())
  File "/home/pablo/.local/lib/python3.10/site-packages/devcellpy/devcellpy.py", line 1204, in main
    predictionAll(pred_normexpr, layer_paths)
  File "/home/pablo/.local/lib/python3.10/site-packages/devcellpy/devcellpy.py", line 317, in predictionAll
    reorder_pickle(val_normexpr, featurenames)
  File "/home/pablo/.local/lib/python3.10/site-packages/devcellpy/devcellpy.py", line 391, in reorder_pickle
    if train_normexpr[-3:] == 'csv':
NameError: name 'train_normexpr' is not defined

I don't really understand why the error is associated to "train_normexpr", because this is just used when runMode= predictAll or featureRankingOne.

Could you please help me understand what I could be doing wrong?

Thanks in advance

Pablo

**Comment by sidrayx** [comment]
Apologies for the delay, it seems that you may be using a previous version of devCellPy that has not been updated on our PyPI. Please clone the GitHub for the time being as that is the most recent and updated copy.

**Comment by fxgaldos** [comment]
Closing due to inactivity. Please feel free to reopen if you have any more questions!
